MYSQL_HOST = ''
MYSQL_PORT = 3306
MYSQL_USER = ''
MYSQL_PASSWORD = ''
MYSQL_DATABASE = 'old_db'
MYSQL_TABLE = 'old_table'
MYSQL_BOOL_TABLE_ROWS = ['row1', 'row2']
MYSQL_LIMIT_OFFSET = 0, 5000

POSTGRES_HOST = ''
POSTGRES_PORT = 5432
POSTGRES_USER = ''
POSTGRES_PASSWORD = ''
POSTGRES_DATABASE = 'new_db'
POSTGRES_TABLE = 'new_table'

REPLACE_x00 = ['\x00', ' ']
# REPLACE_x00 = None
